# Plugin created for the Itsn3w French Community @ www.itsnew.fr
name: MagicEgg
author: Ribesg
website: www.itsnew.fr
main: com.github.ribesg.magicegg.MagicEgg
version: 0.2
description: Renforce enchantments with DragonEgg and Cauldrons
load: POSTWORLD